import type { Metadata } from 'next';
import ToolShell from '@/components/tools/ToolShell';
import AiImageDetectorClient from '@/components/tools/AiImageDetectorClient';

export const metadata: Metadata = {
    title: 'Free AI Image Detector — Check if an Image is AI-Generated',
    description:
        'Upload any image to check whether it was generated by AI (Midjourney, DALL·E, Stable Diffusion) or is a real photo. Free, no login required.',
    keywords: [
        'ai image detector',
        'ai image checker',
        'is this image ai generated',
        'detect ai images',
        'midjourney detector',
        'stable diffusion detector',
        'ai art detector',
    ],
    alternates: { canonical: '/tools/ai-image-detector' },
    openGraph: {
        title: 'Free AI Image Detector — Check if an Image is AI-Generated',
        description:
            'Upload any image to check whether it was AI-generated or a real photo. Free, no login required.',
        type: 'website',
    },
};

export default function AiImageDetectorPage() {
    return (
        <ToolShell
            slug="ai-image-detector"
            title="AI Image Detector"
            subtitle="Upload an image to estimate whether it was generated by AI or is a real photo. Works with Midjourney, DALL·E, Stable Diffusion and more."
        >
            <AiImageDetectorClient />
        </ToolShell>
    );
}
