/**
 * Per-tool SEO content: a unique intro, how-to steps, and FAQs for each tool.
 * Rendered on the tool page and emitted as FAQPage / SoftwareApplication JSON-LD.
 * Unique on-page content is what keeps these pages from reading as "thin".
 */

export interface ToolFaq {
    q: string;
    a: string;
}
export interface ToolContent {
    intro: string;
    steps: string[];
    faqs: ToolFaq[];
}

export const TOOL_CONTENT: Record<string, ToolContent> = {
    // ── AI Writing ────────────────────────────────────────────────
    'ai-detector': {
        intro: 'Check whether a piece of text was written by an AI model like ChatGPT, Gemini or Claude. Paste your text and get a probability score in seconds.',
        steps: ['Paste the text you want to check into the box.', 'Click “Detect AI”.', 'Read the AI-probability score and use it as a signal, not proof.'],
        faqs: [
            { q: 'How accurate is the AI detector?', a: 'It is highly accurate on longer passages but no detector is perfect — treat the score as a strong signal, especially for short or heavily edited text.' },
            { q: 'How much text do I need?', a: 'At least a paragraph (about 255 characters) gives the most reliable result.' },
            { q: 'Is my text stored?', a: 'No. Your text is only analysed to produce the score and is not saved.' },
        ],
    },
    'ai-image-detector': {
        intro: 'Find out if an image was generated by AI (Midjourney, DALL·E, Stable Diffusion) or is a real photo. Upload an image and get an AI-probability score.',
        steps: ['Upload or drag in the image you want to check.', 'Click “Detect AI”.', 'Review the AI-probability score.'],
        faqs: [
            { q: 'Which images work best?', a: 'Upload the original, unedited file. Heavy compression, cropping or filters can reduce accuracy.' },
            { q: 'What formats are supported?', a: 'JPG, PNG and WebP up to 8MB.' },
            { q: 'Is my image stored?', a: 'No — it is analysed only to produce the result and is not kept.' },
        ],
    },
    'ai-summarizer': {
        intro: 'Turn long articles, documents or notes into a clear, concise summary. Choose short, medium or long output to fit your needs.',
        steps: ['Paste the text you want to summarise.', 'Pick a summary length.', 'Click “Summarize” and copy the result.'],
        faqs: [
            { q: 'How long can the input be?', a: 'Up to 8,000 characters per summary on the free tool.' },
            { q: 'Will it change the meaning?', a: 'No — the summary preserves the key points and meaning of the original text.' },
            { q: 'Do I need an account?', a: 'No login is required.' },
        ],
    },
    'ai-paraphraser': {
        intro: 'Reword and rephrase any sentence or paragraph while keeping its original meaning. Choose a standard, formal, casual, fluent or simple style.',
        steps: ['Paste the text you want to reword.', 'Choose a style.', 'Click “Paraphrase” and copy the rewritten text.'],
        faqs: [
            { q: 'Does it keep the original meaning?', a: 'Yes — it rewrites the wording while preserving what the text says.' },
            { q: 'Can it make text more formal or casual?', a: 'Yes, pick the style that fits and the tool adapts the wording.' },
            { q: 'Is there a length limit?', a: 'Up to 5,000 characters per request.' },
        ],
    },
    'grammar-checker': {
        intro: 'Fix grammar, spelling and punctuation mistakes in any text while keeping your voice. Paste your writing and get a clean, corrected version.',
        steps: ['Paste the text you want to proofread.', 'Click “Check grammar”.', 'Copy the corrected text.'],
        faqs: [
            { q: 'Does it change my writing style?', a: 'No — it corrects errors while preserving your meaning and tone.' },
            { q: 'What does it fix?', a: 'Grammar, spelling and punctuation.' },
            { q: 'Is it free?', a: 'Yes, and no account is required.' },
        ],
    },
    'ai-translator': {
        intro: 'Translate text naturally between languages. Enter your text, choose a target language, and get an accurate, fluent translation.',
        steps: ['Paste the text you want to translate.', 'Type the language to translate into.', 'Click “Translate” and copy the result.'],
        faqs: [
            { q: 'Which languages are supported?', a: 'Most major world languages — just type the language you want.' },
            { q: 'Is it a literal translation?', a: 'No — it produces natural, fluent translations rather than word-for-word.' },
            { q: 'Is there a limit?', a: 'Up to 5,000 characters per translation.' },
        ],
    },
    'word-counter': {
        intro: 'Count words, characters, sentences, paragraphs and reading time as you type. Everything runs in your browser — nothing is uploaded.',
        steps: ['Type or paste your text into the box.', 'Watch the live counts update instantly.', 'Use the reading-time estimate to plan your content.'],
        faqs: [
            { q: 'Is my text sent anywhere?', a: 'No — counting happens entirely in your browser, so your text never leaves your device.' },
            { q: 'How is reading time calculated?', a: 'Based on an average reading speed of about 200 words per minute.' },
            { q: 'Is there a character limit?', a: 'No — paste as much text as you like.' },
        ],
    },

    // ── Image ─────────────────────────────────────────────────────
    'image-compressor': {
        intro: 'Reduce the file size of JPG, PNG and WebP images with an adjustable quality slider. Your images are compressed in your browser and never uploaded.',
        steps: ['Upload or drag in your image.', 'Set the quality level.', 'Click “Compress” and download the smaller file.'],
        faqs: [
            { q: 'Are my images uploaded to a server?', a: 'No — compression runs entirely in your browser, so your images stay private.' },
            { q: 'How much smaller will my image be?', a: 'It depends on the quality you choose; the result shows the exact size and percentage saved.' },
            { q: 'What formats work?', a: 'JPG, PNG and WebP.' },
        ],
    },
    'image-resizer': {
        intro: 'Resize any image to exact pixel dimensions, with an optional aspect-ratio lock. Runs locally in your browser — no upload needed.',
        steps: ['Upload your image.', 'Enter the width and height you want.', 'Click “Resize” and download the result.'],
        faqs: [
            { q: 'Can I keep the aspect ratio?', a: 'Yes — leave the lock enabled and the other dimension adjusts automatically.' },
            { q: 'Are my images private?', a: 'Yes — resizing happens in your browser and nothing is uploaded.' },
            { q: 'Which formats are supported?', a: 'JPG, PNG and WebP.' },
        ],
    },
    'image-converter': {
        intro: 'Convert images between JPG, PNG and WebP in one click. Everything happens in your browser, so your files never leave your device.',
        steps: ['Upload the image you want to convert.', 'Pick the output format (JPG, PNG or WebP).', 'Click “Convert” and download.'],
        faqs: [
            { q: 'Is there any quality loss?', a: 'Conversion uses high quality settings; converting to PNG is lossless, JPG and WebP use near-original quality.' },
            { q: 'Are my files uploaded?', a: 'No — conversion is done locally in your browser.' },
            { q: 'Can I convert WebP to JPG?', a: 'Yes — convert between any of JPG, PNG and WebP.' },
        ],
    },
    watermark: {
        intro: 'Add a text watermark to your photos with adjustable position, opacity and size. Protect your images without uploading them anywhere.',
        steps: ['Upload your image.', 'Type your watermark text and set position, opacity and size.', 'Click “Add watermark” and download.'],
        faqs: [
            { q: 'Can I tile the watermark across the image?', a: 'Yes — choose the “Tiled” position to repeat it diagonally across the whole image.' },
            { q: 'Are my images uploaded?', a: 'No — the watermark is applied in your browser.' },
            { q: 'Can I change the opacity?', a: 'Yes — adjust opacity and size with the sliders.' },
        ],
    },

    // ── Video ─────────────────────────────────────────────────────
    'video-compressor': {
        intro: 'Shrink a video’s file size with an adjustable quality level. Processing runs entirely in your browser — best for short clips like reels and TikToks.',
        steps: ['Upload your video.', 'Set the quality level.', 'Click “Compress” and download the smaller video.'],
        faqs: [
            { q: 'Is my video uploaded?', a: 'No — compression runs in your browser using WebAssembly, so your video stays on your device.' },
            { q: 'How long can the video be?', a: 'It works best on short clips; very long videos may be slow or hit browser memory limits.' },
            { q: 'What format is the output?', a: 'MP4 (H.264).' },
        ],
    },
    'video-converter': {
        intro: 'Convert video to MP4, WebM or animated GIF right in your browser. No upload, no watermark, no login.',
        steps: ['Upload your video.', 'Choose the output format (MP4, WebM or GIF).', 'Click “Convert” and download.'],
        faqs: [
            { q: 'Can I turn a video into a GIF?', a: 'Yes — choose GIF as the output format.' },
            { q: 'Is my video uploaded?', a: 'No — conversion happens locally in your browser.' },
            { q: 'What about long videos?', a: 'Short clips work best; long videos may be slow in the browser.' },
        ],
    },
    'video-trimmer': {
        intro: 'Cut a clip out of any video by dragging two handles on a timeline. Everything is processed privately in your browser.',
        steps: ['Upload your video.', 'Drag the start and end handles to select the clip.', 'Click “Trim” and download the cut.'],
        faqs: [
            { q: 'Is trimming fast?', a: 'Yes — it copies the video stream without re-encoding, so it is quick and lossless.' },
            { q: 'Is my video uploaded?', a: 'No — trimming runs in your browser.' },
            { q: 'Can I preview the cut points?', a: 'Yes — the video scrubs to each handle as you drag it.' },
        ],
    },
    'audio-extractor': {
        intro: 'Extract the audio track from any video as an MP3 or WAV file. Runs in your browser — no upload, no watermark.',
        steps: ['Upload a video or audio file.', 'Choose MP3 or WAV.', 'Click “Extract audio” and download.'],
        faqs: [
            { q: 'Can I convert MP4 to MP3?', a: 'Yes — upload the MP4 and choose MP3 output.' },
            { q: 'Is my file uploaded?', a: 'No — extraction happens locally in your browser.' },
            { q: 'What quality is the MP3?', a: 'High quality (VBR ~190kbps).' },
        ],
    },
    'subtitle-generator': {
        intro: 'Automatically generate subtitles and a transcript from a video URL or an audio/video file. Download ready-to-use SRT and VTT caption files.',
        steps: ['Paste a video URL or upload a file.', 'Click “Generate subtitles”.', 'Copy the transcript or download the SRT/VTT files.'],
        faqs: [
            { q: 'What subtitle formats do I get?', a: 'Both SRT and VTT, plus a plain-text transcript.' },
            { q: 'Which platforms work with URLs?', a: 'Instagram, TikTok, Facebook and more; for YouTube, uploading the file is most reliable.' },
            { q: 'How accurate are the subtitles?', a: 'Very accurate, but quick-review names and jargon before publishing.' },
        ],
    },

    // ── Creator ───────────────────────────────────────────────────
    'caption-generator': {
        intro: 'Generate scroll-stopping social media captions for Instagram, TikTok, YouTube and more. Describe your post and choose a tone.',
        steps: ['Describe what your post is about.', 'Pick a platform and tone.', 'Click “Generate captions” and copy your favourite.'],
        faqs: [
            { q: 'How many captions do I get?', a: 'Three distinct options each time.' },
            { q: 'Which platforms are supported?', a: 'Instagram, TikTok, YouTube, LinkedIn, X and Facebook.' },
            { q: 'Can I set the tone?', a: 'Yes — casual, professional, funny or inspirational.' },
        ],
    },
    'hashtag-generator': {
        intro: 'Find relevant, discoverable hashtags for your next post. Describe your content and pick a platform to get a ready-to-use set.',
        steps: ['Describe what your post is about.', 'Choose a platform.', 'Click “Generate hashtags” and copy them.'],
        faqs: [
            { q: 'How many hashtags do I get?', a: 'Around 15 relevant hashtags per request.' },
            { q: 'Are they tailored to the platform?', a: 'Yes — pick Instagram, TikTok and others for platform-appropriate tags.' },
            { q: 'Do I need an account?', a: 'No login is required.' },
        ],
    },
    'bio-generator': {
        intro: 'Write a catchy profile bio for Instagram, TikTok, X or LinkedIn. Describe yourself and pick a tone to get three bio options.',
        steps: ['Describe yourself or your brand.', 'Choose a platform and tone.', 'Click “Generate bios” and copy your favourite.'],
        faqs: [
            { q: 'How many bios do I get?', a: 'Three distinct options each time.' },
            { q: 'Can I match my platform?', a: 'Yes — choose Instagram, TikTok, X, LinkedIn or general.' },
            { q: 'Can I set the vibe?', a: 'Yes — casual, professional, funny or aesthetic.' },
        ],
    },
    'qr-code-generator': {
        intro: 'Create a QR code from any URL or text and download it as a PNG. Generated instantly in your browser with a few style options.',
        steps: ['Enter a URL or text.', 'Pick a colour style.', 'Download your QR code as a PNG.'],
        faqs: [
            { q: 'Do the QR codes expire?', a: 'No — they encode your link directly and never expire.' },
            { q: 'Can I customise the look?', a: 'Yes — choose from several colour styles.' },
            { q: 'Is it free?', a: 'Yes, and no account is required.' },
        ],
    },
};
